version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"       # LocalStack Gateway
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,dynamodb,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

